INSERT INTO PAY_CARD(ID, BALANCE, CUSTOMER) VALUES (99, 123.45, 'VictorI');
INSERT INTO PAY_CARD(ID, BALANCE, CUSTOMER) VALUES (100, 1.00, 'VictorI');
INSERT INTO PAY_CARD(ID, BALANCE, CUSTOMER) VALUES (101, 150.00, 'VictorI');
INSERT INTO PAY_CARD(ID, BALANCE, CUSTOMER) VALUES (102, 150.00, 'Ben');